version: '3.8'
services:
  mydbsql:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  
  app:
    build: .
    depends_on:
      - mydbsql
    links:
      - mydbsql
    ports:
      - 3000:3000